appsix/urls.py
from django.conf.urls import url
from appsix import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register/', views.register, name='register'),
    # url(r'logout/', views.logout, name='logout'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

prosix/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from appsix import views

app_name = 'appsix'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^appsix/', include('appsix.urls')),
    url(r'^', include('appsix.urls', namespace='appsix')),
    url(r'^user_login/$', views.user_login, name='user_login')
]

appsix/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)
    def __str__(self):
        return self.user.username

appsix/forms.py
from django import forms
from django.contrib.auth.models import User
from appsix.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

appsix/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from appsix.forms import UserProfileInfoForm, UserForm

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    my_dict = {'my_title':'index'}
    return render(request, 'appsix/index.html',context=my_dict)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'appsix/register.html', {'my_title':"register",'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("account inactive")
        else:
            print("someone tried to log in and failed")
            return HttpResponse("invalid login details")
    else:
        return render(request,'appsix/index.html', {"my_title":"index"})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/appsix/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ my_title }}</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css"%}"/>
  </head>
  <body>

    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'register' %}">Register |</a>
    <a href="{% url 'index' %}"> Log in</a>
    {% endif %}
    {% block body_block %}
      #body inserted from other files
    {% endblock %}
  </body>
</html>

templates/appsix/index.html
{% extends "appsix/base.html" %}
{% block body_block %}
  <h1>This is Index</h1>
  <form action="{% url 'appsix:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="enter username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" value="login">
  </form>
{% endblock %}

templates/appsix/register.html
<!DOCTYPE html>
{% extends "appsix/base.html" %}
{% block body_block %}

  {% if registered %}
    <h1>registered</h1>
  {% else %}
    <h1>Register here</h1>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p}}
      <input type="submit" value="register">
    </form>
  {% endif %}
{% endblock %}